name: CMake for MacOS

on: workflow_dispatch

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.0'
        host: 'mac'
        target: 'desktop'
        arch: 'clang_64'
        install-deps: 'true'
        modules: 'qt5compat'
        cache: 'true'
        set-env: 'true'

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

 #   - name: Test
 #     working-directory: ${{github.workspace}}/build
 #     # Execute tests defined by the CMake configuration.
 #     # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
 #     run: ctest -C ${{env.BUILD_TYPE}}

    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
       name: tea-mac-binary
       path: ${{github.workspace}}/build/tea.app
